### ISSUE TITLE
Unexpected behavior: 106.0a1 and 106.0a2 are equal

### ISSUE THREAD

**Issue by Tobi823** [G00fY2/version-compare#12]
If a version number contains a letter, the rest after the letter is ignored.
`Version("106.0a1", true) == Version("106.0a2", true)` evaluates to true 
`Version("106.0.a.1", true) == Version("106.0.b.2", true)` evaluates to true 

My solution (I don't know it is good enough) is to convert every letter to its Unicode code + own subversion:
```
val rawVersion = "106.0a1"
        var cleanedUpVersion = ""
        for (character: Char in rawVersion) {
            if (character.isDigit() || character == '.') {
                cleanedUpVersion += character
            } else {
                if (!cleanedUpVersion.endsWith('.')) {
                    cleanedUpVersion += '.'
                }
                cleanedUpVersion += character.code.toString()
                cleanedUpVersion += '.'
            }
        }

```
This code converts "106.0a1" to "106.0.97.1"

**Comment by G00fY2** [comment]
Hi @Tobi823, thanks for reaching out.

As you can see in the [version-structure-example](https://github.com/G00fY2/version-compare#version-structure-example) this is actually the intended and expected behavior.

This library was already designed to leniently parse version Strings (e.g. we do not enforce [Semantic Versioning 2.0.0](https://semver.org/lang/)). But I don't think it's the responsibility of this library to "cleanup" version numbers before parsing them.

**Comment by Tobi823** [comment]
I see ... I misread the README.md
