### ISSUE TITLE
Support for "v" prefixes

### ISSUE THREAD

**Issue by mardous** [G00fY2/version-compare#16]
Please add support for version names starting with "v", eg: "v1.0.0", "v1.0.1". That would be great!

**Comment by G00fY2** [comment]
Hi and thanks for reaching out! Since this library is basically feature complete I will not add any new behavior and only fix bugs (which is unlikely that there are any at this point).

If you have version Strings with a "v" prefix I would suggest that you just replace the first char if it's "v" (in Koltin there is e.g. [replaceFirstChar](replaceFirstChar)).

```kotlin
replaceFirstChar { if (it == "v") "" else it.toString() }
```

Maybe at one point I will create a version 2.0 with Kotlin Multiplatform support. In this case I will take your feature request into consideration. ❤️

**Comment by mardous** [comment]
> Hi and thanks for reaching out! Since this library is basically feature complete I will not add any new behavior and only fix bugs (which is unlikely that there are any at this point).
> 
> If you have version Strings with a "v" prefix I would suggest that you just replace the first char if it's "v" (in Koltin there is e.g. [replaceFirstChar](replaceFirstChar)).
> 
> ```kotlin
> replaceFirstChar { if (it == "v") "" else it.toString() }
> ```
> 
> Maybe at one point I will create a version 2.0 with Kotlin Multiplatform support. In this case I will take your feature request into consideration. ❤️

I understand, thanks!
