### ISSUE TITLE
Incorrect parsing for patch version.

### ISSUE THREAD

**Issue by fi8er1** [G00fY2/version-compare#19]
![Screenshot 2024-09-05 at 8 59 33 AM](https://github.com/user-attachments/assets/28c5e8ab-7f8a-41fb-a99f-97dd8a64fe36)

**Comment by G00fY2** [comment]
Hi and thanks for reaching out! 

Please provide a concrete description instead of an screenshot. What are the inputs and what is the expected vs actual result?
 
This library is heavily tested (both in production and with [unit tests](https://github.com/G00fY2/version-compare/blob/main/versioncompare/src/test/java/io/github/g00fy2/versioncompare/VersionHigherLowerTest.java#L18)). You can also manually compare versions using the [sample app](https://github.com/G00fY2/version-compare?tab=readme-ov-file#sample-app).

With the values on your screen the result is:
```kotlin
val appVersion = "1.1.0"
val storeVersion = "1.1.10"
Version(appVersion) < Version(storeVersion) // TRUE
```

So with the inputs you see in the debugger the if-condition is TRUE, which is correct regarding to semantic versioning.

**Comment by fi8er1** [comment]
BuildConfig.VERSION_NAME was "1.1.11" but when it was passed to Version, it got parsed as "1.1.0" 
The screenshot is pretty self explanatory.

**Comment by G00fY2** [comment]
`BuildConfig` fields are auto generated at build time by Gradle. I assume you either run into some build caching issues or any other debugger issue unrelated to the Version Compare lib. If you try this code with hardcoded Strings and you will see everything is working as expected.
