### ISSUE TITLE
making release bigger that pre-releases

### ISSUE THREAD

**Issue by chlegou** [G00fY2/version-compare#2]
i have this comparing in my app, "1.0.3" and "1.0.3-rc1"

i want users to have the possible latest version, so  i'm using `.isAtLeast()` to compare, which **i think** returning a wrong answer. here is my code:

    Boolean isLatest = new Version("1.0.3-rc1").isAtLeast("1.0.3");

since "1.0.3-rc1" is a pre-release, so it shouldn't be the latest release when comparing with "1.0.3".

**i might be mistaking, but this is the logic i could understand. Fix my thoughts if i'm wrong.**

i have found this docs explaining release hierarchy. 
link: https://semver.org/#spec-item-11

**Comment by G00fY2** [comment]
Hi @chlegou, thanks for your feedback. I admit that this method is a bit tricky and I spend some time thinking about the naming of it. I know what behaviour you except.

But from my [documentation](https://g00fy2.github.io/version-compare/com/g00fy2/versioncompare/Version.html#isAtLeast-java.lang.String-) 
> Checks if the Version object is at least as high as otherVersion. This will only compare the parts that exist in otherVersion. Suffixes will always be ignored.

So basically I built this method to return **true**  for "1.0.3-rc1" isAtLeast "1.0.3" (because it has the same version part an I needed this for a specific usecase). In your case you can simply use:

```
Boolean isLatest = new Version("1.0.3-rc1").isEqual("1.0.3") || new Version("1.0.3-rc1").isHigherThan("1.0.3");
```

But I will rethink the naming to make it clearer!

**Comment by chlegou** [comment]
@G00fY2  That would be better, since following the WISWIG (what i see is what i get) rule, methods name should describe what they are actually doing.

for now i will use the code you are suggesting, but expecting to see same behavior in next versions ;) (since not giving since, using a code snippet that behave like an existing named method).

**Comment by G00fY2** [comment]
I agree. Maybe I find some time this weekend to release an update and change the behaviour of **isAtLeast**. Maybe I add a second, optional parameter to allow ignoring the suffix. :)

**Comment by G00fY2** [comment]
Fixed with 1.3.0 (12155ac).

**Comment by chlegou** [comment]
very fascinating! loved it!

just to confirm, `.isAtLeast(str)` is the same as `.isAtLeast(str, false)` right?

**Comment by G00fY2** [comment]
Yes, exactly.

**Comment by chlegou** [comment]
thanks! i really appreciate it! now the code is working as Sharp!
