### ISSUE TITLE
can't get latest version from maven repository

### ISSUE THREAD

**Issue by csonuryilmaz** [G00fY2/version-compare#3]
Hi, I'm trying to include `versioncompare` to my project as a **maven** dependency. But I can't get latest version: `1.3.2`

IDE: `Intellij Idea CE`

![version-1 2 7](https://user-images.githubusercontent.com/7355362/58748767-d163b480-8485-11e9-8aee-1284cbe6189e.png)

Here `remote jar repositories` configuration:
![remote-jar-repositories](https://user-images.githubusercontent.com/7355362/58748816-5d75dc00-8486-11e9-8755-496f38eea1bd.png)

**Comment by G00fY2** [comment]
Hi Onur, thanks for contacting me.

IntelliJ currently does not support searching artifacts on JCenter: https://youtrack.jetbrains.com/v2/issue/IDEA-154970

The reason versioncompare:1.2.7 pops up is because it propably was used as a transive dependency in an library hosted on JFrog Artifactory and therefore is found in the cache. You see this when you query Artifactory: http://repo.jfrog.org/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoidmVyc2lvbmNvbXBhcmUifQ==

If you manually add my library to your pom or replace the version number in the search field you should be fine.👋

**Comment by csonuryilmaz** [comment]
Hi Thomas, thanks a lot for fast and comprehensive reply!

Replacing the version number in the search field not worked **but** manually adding library as a dependency to **pom.xml** with adding `jcenter` repository to maven config worked. :tada: 
:star:++
